### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by clydemcqueen** [ArduPilot/UAVLogViewer#414]
~~~
$ docker build --no-cache -t clydemcqueen/uavlogviewer .
[+] Building 41.1s (8/9)                                                                                                                                   docker:default
 => [internal] load build definition from Dockerfile                                                                                                                 0.0s
 => => transferring dockerfile: 343B                                                                                                                                 0.0s
 => [internal] load metadata for docker.io/library/node:12                                                                                                           0.3s
 => [internal] load .dockerignore                                                                                                                                    0.0s
 => => transferring context: 66B                                                                                                                                     0.0s
 => [1/5] FROM docker.io/library/node:12@sha256:01627afeb110b3054ba4a1405541ca095c8bfca1cb6f2be9479c767a2711879e                                                     0.0s
 => [internal] load build context                                                                                                                                    0.0s
 => => transferring context: 9.39kB                                                                                                                                  0.0s
 => CACHED [2/5] WORKDIR /usr/src/app                                                                                                                                0.0s
 => [3/5] COPY package*.json ./                                                                                                                                      0.1s
 => ERROR [4/5] RUN npm install                                                                                                                                     40.5s
------                                                                                                                                                                    
 > [4/5] RUN npm install:                                                                                                                                                 
0.659 npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but package-lock.json was generated for lockfileVersion@2. I'll try to do my best with it!                                                                                                                                                                 
36.06                                                                                                                                                                     
36.06 > deasync@0.1.27 install /usr/src/app/node_modules/deasync                                                                                                          
36.06 > node ./build.js
36.06 
36.11 `linux-x64-node-12` exists; testing
36.25 Binary is fine; exiting
36.73 
36.73 > node-sass@9.0.0 install /usr/src/app/node_modules/node-sass
36.73 > node scripts/install.js
36.73 
36.97 Downloading binary from https://github.com/sass/node-sass/releases/download/v9.0.0/linux-x64-72_binding.node
37.16 Download complete
37.16 Binary saved to /usr/src/app/node_modules/node-sass/vendor/linux-x64-72/binding.node
37.20 Caching binary to /root/.npm/node-sass/9.0.0/linux-x64-72_binding.node
37.32 
37.32 > @fortawesome/fontawesome-common-types@6.4.0 postinstall /usr/src/app/node_modules/@fortawesome/fontawesome-common-types
37.32 > node attribution.js
37.32 
37.36 Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
37.36 License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
37.36 Copyright 2023 Fonticons, Inc.
37.36 
37.50 
37.50 > core-js@2.6.12 postinstall /usr/src/app/node_modules/core-js
37.50 > node -e "try{require('./postinstall')}catch(e){}"
37.50 
37.54 Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!
37.54 
37.54 The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
37.54 > https://opencollective.com/core-js 
37.54 > https://www.patreon.com/zloirock 
37.54 
37.54 Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)
37.54 
37.91 
37.91 > protobufjs@7.2.6 postinstall /usr/src/app/node_modules/protobufjs
37.91 > node scripts/postinstall
37.91 
38.13 
38.13 > es5-ext@0.10.62 postinstall /usr/src/app/node_modules/es5-ext
38.13 >  node -e "try{require('./_postinstall')}catch(e){}" || exit 0
38.13 
38.36 
38.36 > @fortawesome/free-solid-svg-icons@6.4.0 postinstall /usr/src/app/node_modules/@fortawesome/free-solid-svg-icons
38.36 > node attribution.js
38.36 
38.40 Font Awesome Free 6.4.0 by @fontawesome - https://fontawesome.com
38.40 License - https://fontawesome.com/license/free (Icons: CC BY 4.0, Fonts: SIL OFL 1.1, Code: MIT License)
38.40 Copyright 2023 Fonticons, Inc.
38.40 
38.41 
38.41 > bootstrap-vue@2.22.0 postinstall /usr/src/app/node_modules/bootstrap-vue
38.41 > opencollective || exit 0
38.41 
38.58                                                              
38.58                           ;iiiiiiiiiiSSSSSSSSiiiiiiiiii;     
38.58                           .rXXXXXXXXXrrrrrrrSXXXXXXXXXr.     
38.58                           :iXXXXXXXX2. ;;;;, r3XXXXXXXi;     
38.58                          ,rSSSSSXXXX2..sSSi: r3XXXSSSSSr,    
38.58                           ,siiiiS2XX2. :;;:,.rXX2Siiiis,     
38.58                            ,riiiii2X2..5XXXi .22iiiiir,      
38.58                             .riiiii22..::::,,r2iiiiir.       
38.58                              .riiiii5SSiiiiS22iiiiir.        
38.58                                ;iiiii5X3333X5iiiii;          
38.58                                 :iiiiiSXXXXSiiiii:           
38.58                                  :siiiiSXXSiiiis:            
38.58                                   ,siiiiiiiiiis,             
38.58                                    .riiiiiiiir.              
38.58                                     .riiiiiir.               
38.58                                      .;iiii;.                
38.58                                        ;ii;                  
38.58                                         ::                   
38.58                                          
38.58                        Thanks for installing bootstrap-vue 
38.58                  Please consider donating to our open collective
38.58                         to help us maintain this package.
38.58                                          
38.58                             Number of contributors: 0
38.58                               Number of backers: 505
38.58                               Annual budget: $34,108
38.58                              Current balance: $63,852
38.58                                          
38.58               Donate: https://opencollective.com/bootstrap-vue/donate
38.58                                          
38.60 
38.60 > node-sass@9.0.0 postinstall /usr/src/app/node_modules/node-sass
38.60 > node scripts/build.js
38.60 
38.72 Binary found at /usr/src/app/node_modules/node-sass/vendor/linux-x64-72/binding.node
38.72 Testing binary
38.80 Binary has a problem: Error: /usr/src/app/node_modules/node-sass/vendor/linux-x64-72/binding.node: file too short
38.80     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1057:18)
38.80     at Module.load (internal/modules/cjs/loader.js:863:32)
38.80     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
38.80     at Module.require (internal/modules/cjs/loader.js:887:19)
38.80     at require (internal/modules/cjs/helpers.js:74:18)
38.80     at module.exports (/usr/src/app/node_modules/node-sass/lib/binding.js:19:10)
38.80     at Object.<anonymous> (/usr/src/app/node_modules/node-sass/lib/index.js:13:35)
38.80     at Module._compile (internal/modules/cjs/loader.js:999:30)
38.80     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
38.80     at Module.load (internal/modules/cjs/loader.js:863:32)
38.80 Building the binary locally
38.80 Building: /usr/local/bin/node /usr/src/app/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
38.86 gyp info it worked if it ends with ok
38.87 gyp verb cli [
38.87 gyp verb cli   '/usr/local/bin/node',
38.87 gyp verb cli   '/usr/src/app/node_modules/node-gyp/bin/node-gyp.js',
38.87 gyp verb cli   'rebuild',
38.87 gyp verb cli   '--verbose',
38.87 gyp verb cli   '--libsass_ext=',
38.87 gyp verb cli   '--libsass_cflags=',
38.87 gyp verb cli   '--libsass_ldflags=',
38.87 gyp verb cli   '--libsass_library='
38.87 gyp verb cli ]
38.87 gyp info using node-gyp@8.4.1
38.87 gyp info using node@12.22.12 | linux | x64
38.87 gyp verb command rebuild []
38.87 gyp verb command clean []
38.87 gyp verb clean removing "build" directory
38.88 gyp verb command configure []
38.90 gyp verb find Python Python is not set from command line or npm configuration
38.90 gyp verb find Python Python is not set from environment variable PYTHON
38.90 gyp verb find Python checking if "python3" can be used
38.90 gyp verb find Python - executing "python3" to get executable path
38.92 gyp verb find Python - executable path is "/usr/bin/python3"
38.92 gyp verb find Python - executing "/usr/bin/python3" to get version
38.94 gyp verb find Python - version is "3.5.3"
38.94 gyp verb find Python - version is 3.5.3 - should be >=3.6.0
38.94 gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
38.94 gyp verb find Python checking if "python" can be used
38.94 gyp verb find Python - executing "python" to get executable path
38.95 gyp verb find Python - executable path is "/usr/bin/python"
38.95 gyp verb find Python - executing "/usr/bin/python" to get version
38.96 gyp verb find Python - version is "2.7.13"
38.96 gyp verb find Python - version is 2.7.13 - should be >=3.6.0
38.96 gyp verb find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
38.96 gyp ERR! find Python 
38.96 gyp ERR! find Python Python is not set from command line or npm configuration
38.96 gyp ERR! find Python Python is not set from environment variable PYTHON
38.96 gyp ERR! find Python checking if "python3" can be used
38.96 gyp ERR! find Python - executable path is "/usr/bin/python3"
38.96 gyp ERR! find Python - version is "3.5.3"
38.96 gyp ERR! find Python - version is 3.5.3 - should be >=3.6.0
38.96 gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
38.96 gyp ERR! find Python checking if "python" can be used
38.96 gyp ERR! find Python - executable path is "/usr/bin/python"
38.96 gyp ERR! find Python - version is "2.7.13"
38.96 gyp ERR! find Python - version is 2.7.13 - should be >=3.6.0
38.96 gyp ERR! find Python - THIS VERSION OF PYTHON IS NOT SUPPORTED
38.96 gyp ERR! find Python 
38.96 gyp ERR! find Python **********************************************************
38.96 gyp ERR! find Python You need to install the latest version of Python.
38.96 gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
38.96 gyp ERR! find Python you can try one of the following options:
38.96 gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
38.96 gyp ERR! find Python   (accepted by both node-gyp and npm)
38.96 gyp ERR! find Python - Set the environment variable PYTHON
38.96 gyp ERR! find Python - Set the npm configuration variable python:
38.96 gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
38.96 gyp ERR! find Python For more information consult the documentation at:
38.96 gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
38.96 gyp ERR! find Python **********************************************************
38.96 gyp ERR! find Python 
38.96 gyp ERR! configure error 
38.96 gyp ERR! stack Error: Could not find any Python installation to use
38.96 gyp ERR! stack     at PythonFinder.fail (/usr/src/app/node_modules/node-gyp/lib/find-python.js:330:47)
38.96 gyp ERR! stack     at PythonFinder.runChecks (/usr/src/app/node_modules/node-gyp/lib/find-python.js:159:21)
38.96 gyp ERR! stack     at PythonFinder.<anonymous> (/usr/src/app/node_modules/node-gyp/lib/find-python.js:266:16)
38.96 gyp ERR! stack     at PythonFinder.execFileCallback (/usr/src/app/node_modules/node-gyp/lib/find-python.js:297:7)
38.96 gyp ERR! stack     at ChildProcess.exithandler (child_process.js:299:7)
38.96 gyp ERR! stack     at ChildProcess.emit (events.js:314:20)
38.96 gyp ERR! stack     at maybeClose (internal/child_process.js:1022:16)
38.96 gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
38.96 gyp ERR! System Linux 6.5.0-27-generic
38.96 gyp ERR! command "/usr/local/bin/node" "/usr/src/app/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
38.96 gyp ERR! cwd /usr/src/app/node_modules/node-sass
38.96 gyp ERR! node -v v12.22.12
38.96 gyp ERR! node-gyp -v v8.4.1
38.96 gyp ERR! not ok 
38.97 Build failed with error code: 1
40.18 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-runtime/node_modules/fsevents):
40.18 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.19 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-runner/node_modules/fsevents):
40.19 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.19 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/jest-config/node_modules/fsevents):
40.19 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.20 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@jest/test-sequencer/node_modules/fsevents):
40.20 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.21 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@jest/environment/node_modules/fsevents):
40.21 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.21 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@jest/reporters/node_modules/fsevents):
40.21 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.22 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.13 (node_modules/@jest/core/node_modules/fsevents):
40.22 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.23 npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.3.2 (node_modules/fsevents):
40.23 npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
40.23 
40.24 npm ERR! code ELIFECYCLE
40.24 npm ERR! errno 1
40.24 npm ERR! node-sass@9.0.0 postinstall: `node scripts/build.js`
40.24 npm ERR! Exit status 1
40.24 npm ERR! 
40.24 npm ERR! Failed at the node-sass@9.0.0 postinstall script.
40.24 npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
40.26 
40.26 npm ERR! A complete log of this run can be found in:
40.26 npm ERR!     /root/.npm/_logs/2024-04-17T19_44_28_576Z-debug.log
------
Dockerfile:11
--------------------
   9 |     COPY package*.json ./
  10 |     
  11 | >>> RUN npm install
  12 |     
  13 |     # Bundle app source
--------------------
ERROR: failed to solve: process "/bin/sh -c npm install" did not complete successfully: exit code: 1

~~~

**Comment by yegawong** [comment]
try to 
FROM node:20

**Comment by AspenEyers** [comment]
I had the same issue, modifying the docker file to use `FROM node:20` worked for me

**Comment by bedaberner** [comment]
I fixed this in https://github.com/ArduPilot/UAVLogViewer/pull/431, this can be closed.
